### PR TITLE
Create no_of_distinct_subsequences.cpp

### PR DESCRIPTION
**Pull request by raj-khanna1**
plz add hacktoberfest label bcoz it's in the hacktoberfest rule.

### CODE REVIEW

**Comment by prabhjotschugh** [comment]
You have to add this file in the arrays folder. Do not create a file directly.

**Comment by raj-khanna1** [comment]
ok bhaiya.

**Comment by prabhjotschugh** [comment]
Raj you will have to close this PR and create a new one. Just add one file in arrays and remove the previous file, and also check the spelling of the file "distinct" not "ditinct"

**Comment by prabhjotschugh** [comment]
wait, i'll help you out in this.
Do not close the PR

**Comment by prabhjotschugh** [comment]
Please consider starring this repository so that more people can discover it and potentially contribute.

**Pull request merged**
