### PR TITLE
Create is_duplicate_subtree_in_tree.cpp

### PR DESCRIPTION
**Pull request by raj-khanna1**
added cpp code of duplicate_subtree_in_tree .
#hacktoberfest

### CODE REVIEW

**Comment by raj-khanna1** [comment]
plz accept add lables bhaiya.

**Comment by prabhjotschugh** [comment]
Good job. Labels already there on repo.

**Comment by prabhjotschugh** [comment]
Star the repo also.

**Comment by raj-khanna1** [comment]
bhaiya in hacktoberfest they are showing this as not accepted pr.

**Comment by prabhjotschugh** [comment]
Refresh kro.. thodi der me show krega.

**Comment by raj-khanna1** [comment]
ha bhaiya , abhi test face mai hai

**Comment by raj-khanna1** [comment]
kya pull request ya issue mai hacktoberfest label nhi ho tab bhi chlega bhaiya?

**Comment by prabhjotschugh** [comment]
Nhi.. mere repo k label me h hacktoberfest h tabhi chal raha h.. vrna nhi chalega

**Pull request merged**
